### ISSUE TITLE
Error with demuxEM

### ISSUE THREAD

**Issue by chris-mcginnis-ucsf** [klarman-cell-observatory/KCO#10]
Hello,

I am having trouble running demuxEM using Terra (has been stalled out at the creating workspace step for ~2hrs now...). So I remembered you all sent me a docker version of scCloud about 6 months ago so I tried to run manually from this.

I recreated the docker container with: 

docker run -it --name demuxEM regevlab/sccloud

I then copied my sample barcode CSVs and raw H5 files into this environment with:

docker cp /Volumes/MULTIseq_1/SLNR_PBMC/demuxEM/barTable_multi_EM.csv demuxEM:/SLNR/barTable_multi_EM.csv
docker cp /Volumes/MULTIseq_1/SLNR_PBMC/demuxEM/barTable_hash_EM.csv demuxEM:/SLNR/barTable_hash_EM.csv
docker cp /Volumes/MULTIseq_1/SLNR_PBMC/demuxEM/raw_feature_bc_matrix.h5 demuxEM:/SLNR/raw_feature_bc_matrix.h5

I then tried to run demuxEM with the following command:

scCloud demuxEM -p 8 --hash-type cell-hashing --generate-diagnostic-plots ./barTable_multi_EM.csv ./raw_feature_bc_matrix.h5 ./SLNR_L3_multi_demux

And got the following error:

ADT file is loaded.
Traceback (most recent call last):
  File "/opt/conda/bin/scCloud", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/scCloud/__main__.py", line 59, in main
    command.execute()   
  File "/opt/conda/lib/python3.6/site-packages/scCloud/commands/DemuxEM.py", line 60, in execute
    run_demuxEM_pipeline(self.args['<input_adt_csv_file>'], self.args['<input_raw_gene_bc_matrices_h5.h5>'], self.args['<output_name>'], **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/scCloud/pipeline/demuxEM_pipeline.py", line 19, in run_demuxEM_pipeline
    data = tools.read_input(input_rna_file, genome = kwargs['genome'], demux_ngene = kwargs['min_num_genes'])
  File "/opt/conda/lib/python3.6/site-packages/scCloud/tools/preprocessing.py", line 201, in read_input
    data = read_10x_h5_file(input_file, genome, return_a_dict, demux_ngene)
  File "/opt/conda/lib/python3.6/site-packages/scCloud/tools/preprocessing.py", line 46, in read_10x_h5_file
    gdmap = load_10x_h5_file(input_h5) # gdmap , genome-data map
  File "/opt/conda/lib/python3.6/site-packages/scCloud/tools/manage_10x_h5_matrices.py", line 43, in load_10x_h5_file
    for node in h5_in.walk_nodes("/" + genome, "Array"):
  File "/opt/conda/lib/python3.6/site-packages/tables/file.py", line 2128, in walk_nodes
    for group in self.walk_groups(where):
  File "/opt/conda/lib/python3.6/site-packages/tables/file.py", line 2146, in walk_groups
    group = self.get_node(where)  # Does the parent exist?
  File "/opt/conda/lib/python3.6/site-packages/tables/file.py", line 1651, in get_node
    node = self._get_node(nodepath)
  File "/opt/conda/lib/python3.6/site-packages/tables/file.py", line 1599, in _get_node
    node = self._node_manager.get_node(nodepath)
  File "/opt/conda/lib/python3.6/site-packages/tables/file.py", line 437, in get_node
    node = self.node_factory(key)
  File "/opt/conda/lib/python3.6/site-packages/tables/group.py", line 1182, in _g_load_child
    node_type = self._g_check_has_child(childname)
  File "/opt/conda/lib/python3.6/site-packages/tables/group.py", line 399, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``/features``

Any advice? As an aside, it would be great if the software was available for use locally instead of depending on Terra.

Chris

**Comment by yihming** [comment]
Hello Chris,

Thanks for reaching! 

You may want to try out our python package, which has just been published on PyPI (pip install scCloud), and see if the same error appears again. 

Also, please notice that the demuxEM command options have been changed in this more recent version. You can type "scCloud demuxEM -h" in terminal to see how they look like. 

Feel free to let us know if the issue still happens, and we would be more than happy to help!


Sincerely,
Yiming

**Comment by chris-mcginnis-ucsf** [comment]
Got it working, thanks!

**Comment by yihming** [comment]
No problem!
