### ISSUE TITLE
Error installing hnswlib-modified

### ISSUE THREAD

**Issue by ccruizm** [klarman-cell-observatory/KCO#11]
Good day,

I am about to do some nuclei multiplexing and have installed scCloud to do the demultiplexing of the libraries. I still do not have the data to test the pipeline, however during installation I had an error installing `hnswlib-modified`. I am using anaconda in an HPC and followed the instructions for installation. I do not know if this library will affect the performance of the pipeline in general. Please find below the error.

```
Building wheel for hnswlib-modified (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/cruiz/anaconda3/envs/scCloud/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0j6sfujv/hnswlib-modified/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0j6sfujv/hnswlib-modified/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-zlqdgvkq --python-tag cp37
       cwd: /tmp/pip-install-0j6sfujv/hnswlib-modified/
  Complete output (41 lines):������
  running bdist_wheel��������������
  running build��������������������
  running build_ext����������������
  creating tmp���������������������
  gcc -pthread -B /home/cruiz/anaconda3/envs/scCloud/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/cruiz/anaconda3/envs/scCloud/include/python3.7m -c /tmp/tmptes_7btu.cpp -o tmp/tmptes_7btu.o -std=c++14
  gcc: error: unrecognized command line option '-std=c++14'
  gcc -pthread -B /home/cruiz/anaconda3/envs/scCloud/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/cruiz/anaconda3/envs/scCloud/include/python3.7m -c /tmp/tmpni3h_a8v.cpp -o tmp/tmpni3h_a8v.o -std=c++11
  cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
  gcc -pthread -B /home/cruiz/anaconda3/envs/scCloud/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/cruiz/anaconda3/envs/scCloud/include/python3.7m -c /tmp/tmp95mfmhcx.cpp -o tmp/tmp95mfmhcx.o -fvisibility=hidden
  cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-0j6sfujv/hnswlib-modified/setup.py", line 117, in <module>
      zip_safe=False,
    File "/home/cruiz/anaconda3/envs/scCloud/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/cruiz/anaconda3/envs/scCloud/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/cruiz/anaconda3/envs/scCloud/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/cruiz/anaconda3/envs/scCloud/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/cruiz/anaconda3/envs/scCloud/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/home/cruiz/anaconda3/envs/scCloud/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/cruiz/anaconda3/envs/scCloud/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/cruiz/anaconda3/envs/scCloud/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/cruiz/anaconda3/envs/scCloud/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/cruiz/anaconda3/envs/scCloud/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/cruiz/anaconda3/envs/scCloud/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 78, in run
      _build_ext.run(self)
    File "/home/cruiz/anaconda3/envs/scCloud/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-install-0j6sfujv/hnswlib-modified/setup.py", line 88, in build_extensions
      import pybind11
  ModuleNotFoundError: No module named 'pybind11'
  ----------------------------------------
  ERROR: Failed building wheel for hnswlib-modified
```

All the other packages were installed:

```
Successfully built loompy docopt fisher-modified leidenalg louvain-github MulticoreTSNE-modified retrying python-igraph
Failed to build hnswlib-modified
Installing collected packages: pybind11, hnswlib-modified, Cython, six, h5py, scipy, python-dateutil, pytz, pandas, loompy, cycler, pyparsing, kiwisolver, matplotlib, pyarrow, retrying, plotly, scikit-misc, xlsxwriter, natsort, joblib, scikit-learn, patsy, statsmodels, docopt, fisher-modified, llvmlite, numba, umap-learn, python-igraph, leidenalg, seaborn, louvain-github, lightgbm, pycparser, cffi, MulticoreTSNE-modified, numexpr, mock, tables, anndata-modified, scCloud
  Running setup.py install for hnswlib-modified ... done
Successfully installed Cython-0.29.13 MulticoreTSNE-modified-0.1 anndata-modified-0.6.4.post2 cffi-1.12.3 cycler-0.10.0 docopt-0.6.2 fisher-modified-0.1.5 h5py-2.9.0 hnswlib-modified-0.3.post2 joblib-0.13.2 kiwisolver-1.1.0 leidenalg-0.7.0 lightgbm-2.2.1 llvmlite-0.29.0 loompy-2.0.17 louvain-github-0.6.1.post1 matplotlib-3.1.1 mock-3.0.5 natsort-6.0.0 numba-0.43.1 numexpr-2.6.9 pandas-0.25.0 patsy-0.5.1 plotly-4.0.0 pyarrow-0.14.1 pybind11-2.3.0 pycparser-2.19 pyparsing-2.4.2 python-dateutil-2.8.0 python-igraph-0.7.1.post6 pytz-2019.2 retrying-1.3.3 scCloud-0.13.0.post2 scikit-learn-0.21.1 scikit-misc-0.1.1 scipy-1.2.1 seaborn-0.9.0 six-1.12.0 statsmodels-0.10.1 tables-3.5.2 umap-learn-0.3.9 xlsxwriter-1.1.8
```
 What would be your recommendation? I just want to have everything ready once I have the data. 

Thanks in advance!

**Comment by yihming** [comment]
Hi,

Actually, if you check the last line starting with "Successfully", hnswlib-modified was installed. And you can confirm it by typing "pip list | grep "hnswlib-modified" " in terminal, which will show information if the package was installed.

The error happens when building hnswlib-modified for the first time, because its dependency pybind11 is not installed. After pip builds all other packages, it will then try to build hnswlib-modified again. Namely, if you first install pybind11, then install scCloud, this error won't appear at the first time building hnswlib-modified.

Hope it helps.


Sincerely,
Yiming

**Comment by yihming** [comment]
BTW, I'm curious about how you find this repository for issues. The package source code is at https://github.com/klarman-cell-observatory/scCloudPy, while this repository is for workflows used at Terra. Ideally, we want users to go to the correct place for issues. If it brought you confusions when you searched for repository of scCloud, please let us know.

Thanks!

**Comment by ccruizm** [comment]
Hello @yihming,

Thank you for your quick reply. I checked and effectively the package was installed successfully. In case of future concerns, I will refer to the correct repository. I googled the name of the package and thought this was the correct one. I will be more careful next time :) Thanks for clearing things up.

**Comment by yihming** [comment]
Hello @ccruizm,

Thank you for your feedback! And sorry for bringing you this confusion. Probably it is not enough to just list the GitHub repo link on the PyPI webpage of scCloud. We will think about the naming issue.
